version: "3.9"

services:
  db:
    image: postgres:13.8-bullseye
    hostname: mm_api-db
    environment:
      POSTGRES_PASSWORD: "mm_api"
      POSTGRES_USER: "mm_api"
      POSTGRES_DB: "mm_api"
    volumes:
    - mm_api-db-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: pg_isready -U mm_api
      interval: 2s
      timeout: 3s
      retries: 40
    ports:
    - "5432:5432"

  redis:
    image: bitnami/redis:6.2.5
    hostname: "mm_api-redis"
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 50

volumes:
  mm_api-db-data:
    name: mm_api-db-data
