"""adding mew mate models

Revision ID: ac3e9575be91
Revises: 2b7380507a71
Create Date: 2024-06-29 14:18:20.160791

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ac3e9575be91"
down_revision = "2b7380507a71"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "falconers",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("permit_class", sa.String(), nullable=False),
        sa.Column("permit_number", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "birds",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("falconer_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("gender", sa.String(), nullable=False),
        sa.Column("species", sa.String(), nullable=False),
        sa.Column(
            "trap_date",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["falconer_id"],
            ["falconers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "weights",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("bird_id", sa.Uuid(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column(
            "w_time",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["bird_id"],
            ["birds.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "feedings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("bird_id", sa.Uuid(), nullable=False),
        sa.Column(
            "f_time",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("food_type", sa.String(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("start_weight_id", sa.Uuid(), nullable=True),
        sa.Column("end_weight_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["bird_id"],
            ["birds.id"],
        ),
        sa.ForeignKeyConstraint(
            ["end_weight_id"],
            ["weights.id"],
        ),
        sa.ForeignKeyConstraint(
            ["start_weight_id"],
            ["weights.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hunts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("bird_id", sa.Uuid(), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=False),
        sa.Column("prey_type", sa.String(), nullable=False),
        sa.Column("prey_count", sa.Integer(), nullable=False),
        sa.Column("notes", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("start_weight_id", sa.Uuid(), nullable=True),
        sa.Column("end_weight_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["bird_id"],
            ["birds.id"],
        ),
        sa.ForeignKeyConstraint(
            ["end_weight_id"],
            ["weights.id"],
        ),
        sa.ForeignKeyConstraint(
            ["start_weight_id"],
            ["weights.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "trainings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("bird_id", sa.Uuid(), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=False),
        sa.Column("training_type", sa.String(), nullable=False),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("performance", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("start_weight_id", sa.Uuid(), nullable=True),
        sa.Column("end_weight_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["bird_id"],
            ["birds.id"],
        ),
        sa.ForeignKeyConstraint(
            ["end_weight_id"],
            ["weights.id"],
        ),
        sa.ForeignKeyConstraint(
            ["start_weight_id"],
            ["weights.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.alter_column(
        "dummy_model",
        "name",
        existing_type=sa.VARCHAR(length=200),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "dummy_model",
        "name",
        existing_type=sa.VARCHAR(length=200),
        nullable=True,
    )
    op.drop_table("trainings")
    op.drop_table("hunts")
    op.drop_table("feedings")
    op.drop_table("weights")
    op.drop_table("birds")
    op.drop_table("falconers")
    # ### end Alembic commands ###
